name: word_speaker
description: A small cross-platform English pronunciation app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cmu_ipa.tsv.gz.part0
    - assets/cmu_ipa.tsv.gz.part1
